### ISSUE TITLE
úkol č. 9

### ISSUE THREAD

**Issue by PavlinaVencovska** [PavlinaVencovska/Python-kurz#8]
https://github.com/PavlinaVencovska/Python-kurz/blob/main/ukol-9.py
https://github.com/PavlinaVencovska/Python-kurz/blob/main/ukol-8.py

Ahoj Andy, ještě odevzdávám devátý úkol, osmý jsem dělala v pondělí po termínu, tak ho jen přihazuju do počtu, nepočítám s tím, že by se počítal. Pandas takhle co se týče základu a těch podmínek, tak snad všecko jasný.
Díky, jdu píct cukroví.

**Comment by andywaltlova** [comment]
Ahoj, oba ukoly jsou v poradku :) nemam nic co bych dodala, ty prikazy jsou docela jasne a vse funguje :heavy_check_mark:
